name: Rust

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install gcc-multilib -y
    - run: rustup target add i686-unknown-linux-gnu
    - run: cargo build --release --verbose
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/i686-unknown-linux-gnu/release/libextest.so
        tag: ${{ inputs.tag || github.ref }}
        overwrite: true
